#!/usr/bin/env bash
# 7-highlander: Displays a message indefinitely and handles SIGTERM

handle_sigterm() {
    echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
